module.exports=function(sequelize,DataTypes){
	return sequelize.define(
		'cinemas',
		{
			id:{
				type:DataTypes.INTEGER,
				primaryKey:true
			},
			name:{
				type:DataTypes.STRING,
				field:'name'
			},
			addr:{
				type:DataTypes.STRING,
				field:'addr'
			},
			vipInfo:{
				type:DataTypes.STRING,
				field:'vipInfo'
			},
			endorse:{
				type:DataTypes.STRING,
				field:'endorse'
			},
			allowRefund:{
				type:DataTypes.STRING,
				field:'allowRefund'
			},
			snack:{
				type:DataTypes.STRING,
				field:'snack'
			},
			vipTag:{
				type:DataTypes.STRING,
				field:'vipTag'
			}
			
		
		}
	)
}