module.exports=function(sequelize,DataTypes){
	return sequelize.define(
		'user',
		{
			id:{
				type:DataTypes.INTEGER,
				primaryKey:true,
				autoIncrement:true
			},
			account:{
				type:DataTypes.STRING,
				field:'account'
			},
			password:{
				type:DataTypes.STRING,
				field:'password'
			},
			salt:{
				type:DataTypes.STRING,
				field:'salt'
			},
			role_id:{
				type:DataTypes.INTEGER,
				field:'role_id'
			}
		}
	)
}